# misc
img_front_topic: '/camera_f/color/image_raw'
img_left_topic: '/camera_l/color/image_raw'
img_right_topic: '/camera_r/color/image_raw'
img_front_depth_topic: '/camera_f/depth/image_raw'
img_left_depth_topic: '/camera_l/depth/image_raw'
img_right_depth_topic: '/camera_r/depth/image_raw'
puppet_arm_left_cmd_topic: '/master/joint_left'
puppet_arm_right_cmd_topic: '/master/joint_right'
puppet_arm_left_topic: '/puppet/joint_left'
puppet_arm_right_topic: '/puppet/joint_right'

robot_base_topic: '/odom_raw'
robot_base_cmd_topic: '/cmd_vel'

use_robot_base: False
publish_rate: 40

arm_steps_length: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.2]
use_depth_image: False


















