# misc
seed: 1
device: cuda

eval: false
onscreen_render: false

agent_class: ACT

robot_infor:
    # camera_sensors: ['rgb_images','depth_images']
    camera_sensors: ['rgb_images']
    camera_names : ['camera_left', 'camera_right', 'camera_top']

    arms : ['puppet']
    controls : ['joint_position', 'end_effector']
                # 'joint_velocity_left', 'joint_velocity_right', 'joint_effort_left', 'joint_effort_right'
    use_robot_base: False
# ACT set
agent_config:
    enc_layers: 4
    dec_layers: 7
    nheads: 8
    hidden_dim: 512
    dim_feedforward: 3200
    backbone: resnet18
    action_dim: 8
    state_dim: 8
    no_encoder: False

    lr_backbone: 0.00001

    lr: 0.0001
    kl_weight: 10

    # others
    use_vq: null
    vq_class: null
    vq_dim: null
